import {Category} from './classes.js';

export const ListOfCategories = [
    new Category("Actor/Actress"),
    new Category("Artwork"),
    new Category("Athlete"),
    new Category("Author"),
    new Category("Band/Musician"),
    new Category("Beverage"),
    new Category("Body Part"),
    new Category("Book Title"),
    new Category("Brand of Clothing"),
    new Category("Building"),
    new Category("Cartoon"),
    new Category("Celebrity Chef"),
    new Category("Children's Game"),
    new Category("Color"),
    new Category("Comic Book Character"),
    new Category("Continent"),
    new Category("Cooking Utensil"),
    new Category("Country"),
    new Category("Crustacean"),
    new Category("Dessert"),
    new Category("Disney Character"),
    new Category("Dog Breed"),
    new Category("Drink"),
    new Category("Electronic Device"),
    new Category("Element on the Periodic Table"),
    new Category("Emoji"),
    new Category("Energy Drink"),
    new Category("Event"),
    new Category("Excuse for Being Late"),
    new Category("Famous Quote"),
    new Category("Fast Food Chain"),
    new Category("Female Name"),
    new Category("Fictional Character"),
    new Category("Fish"),
    new Category("Flower"),
    new Category("Food"),
    new Category("Football Player"),
    new Category("Foreign City"),
    new Category("Furniture"),
    new Category("Game"),
    new Category("Gemstone"),
    new Category("Hobby"),
    new Category("Holiday"),
    new Category("Household Item"),
    new Category("Insect"),
    new Category("Instrument"),
    new Category("Island"),
    new Category("Item in a Souvenir Shop"),
    new Category("Jewelry"),
    new Category("Job"),
    new Category("Juice"),
    new Category("Kitchen Appliance"),
    new Category("Landmark"),
    new Category("Leisure Activity"),
    new Category("Liquor"),
    new Category("Magazine"),
    new Category("Mammal"),
    new Category("Martial Art"),
    new Category("Mathematical Term"),
    new Category("Meal"),
    new Category("Media Title"),
    new Category("Military Weapon"),
    new Category("Mineral"),
    new Category("Mistake"),
    new Category("Movie Title"),
    new Category("Musical Genre"),
    new Category("Musical Instrument"),
    new Category("Mythical Creature"),
    new Category("Natural Disaster"),
    new Category("Newspaper"),
    new Category("Nickname"),
    new Category("Number"),
    new Category("Occupation"),
    new Category("Ocean"),
    new Category("Office Supply"),
    new Category("Opera"),
    new Category("Outdoor Activity"),
    new Category("Painting"),
    new Category("Perfume"),
    new Category("Period of Time"),
    new Category("Personality Trait"),
    new Category("Phobia"),
    new Category("Photography Equipment"),
    new Category("Place to Shop"),
    new Category("Plant"),
    new Category("Poem"),
    new Category("Political Figure"),
    new Category("Pop Song"),
    new Category("Potato Chip Flavor"),
    new Category("Presidential Candidate"),
    new Category("Product"),
    new Category("Professional Athlete"),
    new Category("Psychological Disorder"),
    new Category("Punctuation Mark"),
    new Category("Quotation"),
    new Category("Radio Station"),
    new Category("Reality TV Show"),
    new Category("Recipe"),
    new Category("Religious Figure"),
    new Category("Restaurant Chain"),
    new Category("River"),
    new Category("Weather Phenomenon"),
    new Category("X-Men Character"),
    new Category("Yoga Pose"),
    new Category("Zodiac Sign"),
    new Category("Brand of Clothing"),
    new Category("City in Asia"),
    new Category("Dessert"),
    new Category("Emotion"),
    new Category("Famous Athlete"),
    new Category("Gemstone"),
    new Category("Hobby"),
    new Category("Insect"),
    new Category("Jewelry"),
    new Category("Kitchen Utensil"),
    new Category("Language Spoken in Europe"),
    new Category("Movie Title"),
    new Category("Number"),
    new Category("Occupation"),
    new Category("Pizza Topping"),
    new Category("Question"),
    new Category("Restaurant Chain"),
    new Category("Superhero"),
    new Category("Television Network"),
    new Category("University"),
    new Category("Vegetable that is Orange"),
    new Category("World Leader"),
    new Category("Book of the Bible"),
    new Category("Celebrity Chef"),
    new Category("Dog Breed"),
    new Category("Electronic Device"),
    new Category("Famous Painting"),
    new Category("Geometric Shape"),
    new Category("Herb or Spice"),
    new Category("International Airport"),
    new Category("Joke"),
    new Category("Kind of Candy"),
    new Category("Landform"),
    new Category("Musical Instrument"),
    new Category("Nickname"),
    new Category("Olympic Event"),
    new Category("Pizza Chain"),
    new Category("Quilt Pattern"),
    new Category("Roald Dahl Book"),
    new Category("Sport Played with a Ball"),
    new Category("TV Show Theme Song"),
    new Category("Vehicle Brand"),
    new Category("Word that Rhymes with 'Blue'"),
    new Category("Young Adult Novel"),
    new Category("Zoo Animal"),
    new Category("Brand of Chocolate"),
    new Category("Country in South America"),
    new Category("Disney Villain"),
    new Category("Element of Nature"),
    new Category("Famous Songwriter"),
    new Category("Greek Philosopher"),
    new Category("Historical Event"),
    new Category("Island"),
    new Category("Jazz Musician"),
    new Category("Kind of Soup"),
    new Category("Language Spoken in Asia"),
    new Category("Musical"),
    new Category("Nickname for a Grandparent"),
    new Category("Occupation in the Medical Field"),
    new Category("Plant that Bears Fruit"),
    new Category("Question that Cannot be Answered with 'Yes' or 'No'"),
    new Category("Rapper"),
    new Category("Sitcom"),
    new Category("Type of Tree"),
    new Category("Variety of Apple"),
    new Category("World Religion"),
    new Category("Brand of Chips"),
]
  